services:
  auth-postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: unless-stopped
    env_file: .env.development
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build: .
    container_name: auth-service
    env_file: .env.development
    environment:
      DB_HOST: auth-postgres
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - auth-postgres

volumes:
  pgdata:

