"""VerificationPin id to email

Revision ID: 1bad391efd0c
Revises: 68d14c7a1b43
Create Date: 2025-04-18 00:37:13.409910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bad391efd0c'
down_revision: Union[str, None] = '68d14c7a1b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_pins', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'verification_pins', ['email'])
    op.drop_column('verification_pins', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_pins', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'verification_pins', type_='unique')
    op.drop_column('verification_pins', 'email')
    # ### end Alembic commands ###
