"""migrate models

Revision ID: 395438320584
Revises: 415f8f01a9ed
Create Date: 2025-04-16 17:49:32.403807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '395438320584'
down_revision: Union[str, None] = '415f8f01a9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'lock_until')
    op.drop_column('credentials', 'is_locked')
    op.drop_column('credentials', 'last_failed_login')
    op.drop_column('credentials', 'failed_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('failed_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('credentials', sa.Column('last_failed_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('credentials', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('credentials', sa.Column('lock_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
