"""migrate models

Revision ID: 415f8f01a9ed
Revises: 6045b8d9b08f
Create Date: 2025-04-16 17:43:20.596701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415f8f01a9ed'
down_revision: Union[str, None] = '6045b8d9b08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('failed_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'failed_attempts')
    # ### end Alembic commands ###
