"""Initial migration

Revision ID: 4766c2887222
Revises: 
Create Date: 2025-04-19 18:30:33.997194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = '4766c2887222'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'credentials',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('email', sa.String(), unique=True, index=True, nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=True),
        sa.Column('failed_attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_failed_login', sa.DateTime(), nullable=True),
        sa.Column('is_locked', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('lock_until', sa.DateTime(), nullable=True),
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )

    op.create_table(
        'verification_pins',
        sa.Column('email', sa.String(), primary_key=True, unique=True, nullable=False),
        sa.Column('pin', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('is_valid', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('can_change', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('for_password_recovery', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('incorrect_attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_pins')
    op.drop_table('credentials')
    # ### end Alembic commands ###
