"""add is_blocked colum

Revision ID: a1a38bea287f
Revises: 4766c2887222
Create Date: 2025-06-26 18:00:24.756688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a38bea287f'
down_revision: Union[str, None] = '4766c2887222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'verification_pins', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_pins', type_='unique')
    op.drop_column('credentials', 'is_blocked')
    # ### end Alembic commands ###
