"""add new tables

Revision ID: c5d38a86ade9
Revises: 30572a232377
Create Date: 2025-04-18 14:47:26.067394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d38a86ade9'
down_revision: Union[str, None] = '30572a232377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_pins', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'verification_pins', ['email'])
    op.drop_column('verification_pins', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_pins', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'verification_pins', type_='unique')
    op.drop_column('verification_pins', 'email')
    # ### end Alembic commands ###
