"""Add failed login tracking to Credential

Revision ID: dcb2cbd4d23d
Revises: 8b008c0c5188
Create Date: 2025-04-14 16:27:35.437163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb2cbd4d23d'
down_revision: Union[str, None] = '8b008c0c5188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credentials_email', table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='credentials_pkey')
    )
    op.create_index('ix_credentials_email', 'credentials', ['email'], unique=True)
    # ### end Alembic commands ###
